# Code generated by SdkContractGenerator. DO NOT EDIT.

CONTRACT = {
    "extend-video": {
        "models": [],
        "fields_by_model": {
            "_": {
                "seeds": {
                    "type": "integer"
                },
                "source_task_id": {
                    "required": True
                }
            }
        }
    },
    "text-to-video": {
        "models": ["veo-3.1", "veo-3.1-fast"],
        "fields_by_model": {
            "veo-3.1": {
                "aspect_ratio": {
                    "enum": ["16:9", "9:16", "auto"]
                },
                "duration_seconds": {
                    "enum": [4, 6, 8],
                    "type": "integer"
                },
                "input_mode": {
                    "enum": ["text", "first_and_last_frames", "reference"]
                },
                "seeds": {
                    "type": "integer"
                }
            },
            "veo-3.1-fast": {
                "aspect_ratio": {
                    "enum": ["16:9", "9:16", "auto"]
                },
                "duration_seconds": {
                    "enum": [4, 6, 8],
                    "type": "integer"
                },
                "input_mode": {
                    "enum": ["text", "first_and_last_frames", "reference"]
                },
                "seeds": {
                    "type": "integer"
                }
            }
        }
    },
    "upscale-video": {
        "models": [],
        "fields_by_model": {
            "_": {
                "index": {
                    "type": "integer"
                },
                "output_resolution": {
                    "enum": ["1080p", "4k"]
                }
            }
        }
    }
}
